---
# Check if the minishift cluster is started if not then start the cluster

# Check if minishift is already up and running
- name: "Check if the minishift profile is already up and running"
  shell: "{{ minishift_bin }} status --profile {{ profile }} | head -1 | awk '{print $2}'"
  register: minishift_status

# Start minishift profile locally
- name: "Start minishift profile {{ profile }}"
  shell: "{{ minishift_bin }} start --profile {{ profile }} --cpus {{ cpus }} --disk-size {{ disk_size }} --memory {{ memory }} --openshift-version {{ oc_version }} --iso-url file:///{{ minishift_dest_dir }}/minishift.iso"
  when: minishift_status.stdout == "Stopped" and minishift_external_vm_ip == ""

# Start minishift on an external VM if configured
- name: "Start minishift profile {{ profile }} on the external VM ip {{ minishift_external_vm_ip }}"
  shell: "{{ minishift_bin }} start --profile {{ profile }} --openshift-version {{ oc_version }} --remote-ipaddress {{ minishift_external_vm_ip }} --remote-ssh-user {{ minishift_external_vm_user }} --remote-ssh-key {{ minishift_external_vm_ssh_key_location }}"
  when: minishift_status.stdout == "Stopped" and minishift_external_vm_ip != ""